config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :movies, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :director
  # searchkick => used for elastisearch

  ##########################
  ####### REAL DEAL! #######
  ####### PGSearch!  #######
  ##########################


  include PgSearch::Model

  multisearchable against: [:title, :synopsis]

  pg_search_scope :search_by_title_and_synopsis,
    against: [ :title, :synopsis ],
    using: {
    # @@ -> Full Text # batm
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  pg_search_scope :global_search,
    against: [ :title, :synopsis ],
    associated_against: {
      director: [ :first_name, :last_name ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:title, :synopsis]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    # raise
    if params[:query].present?
      # Multiple columns
      # sql_query = 'title ILIKE :query OR synopsis ILIKE :query'
      # @movies = Movie.where(sql_query, query: "%#{params[:query]}%")

      # multiple models - association
      # sql_query = " \
      #   movies.title ILIKE :query \
      #   OR movies.synopsis ILIKE :query \
      #   OR directors.first_name ILIKE :query \
      #   OR directors.last_name ILIKE :query \
      # "

      # PG Full-text Search
      # LIKE -> search for characters, order matter!
      # dog
      # dogs dogville

      # FULL TEXT
      # JUMP
      # jumping, jumps, jumped

      # FullSearch
      # sql_query = " \
      #   movies.title @@ :query \
      #   OR movies.synopsis @@ :query \
      #   OR directors.first_name @@ :query \
      #   OR directors.last_name @@ :query \
      # "

      # # jump -> jumping jumps jumped
      # @movies = Movie.joins(:director).where(sql_query, query: "%#{params[:query]}%")

      # @movies = Movie.search_by_title_and_synopsis(params[:query])

      # @movies = Movie.global_search(params[:query])
      @movies = PgSearch.multisearch(params[:query])
    else
      @movies = Movie.all
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImdbSearchLecture</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <%= form_tag movies_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a movie"
        %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-12 col-sm-8" id='movies'>
      <% @movies.each do |movie| %>
        <h3><%= movie.title %></h3>
        <p><%= movie.synopsis %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="row justify-content-center my-5">
    <div class="col-12">
      <%= link_to "Browse movies", movies_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>